USE madredeus_db;

-- Expansión de la tabla students
ALTER TABLE students
ADD COLUMN photo VARCHAR(255) DEFAULT NULL,
ADD COLUMN birth_place VARCHAR(150) DEFAULT NULL,
ADD COLUMN document_type ENUM('CI', 'DNI', 'Pasaporte', 'Precaria') DEFAULT 'DNI',
ADD COLUMN civil_status ENUM('Soltero', 'Casado', 'Divorciado', 'Viudo') DEFAULT 'Soltero',
ADD COLUMN max_education_level ENUM('Primario', 'Secundario', 'Terciario', 'Universitario') DEFAULT 'Secundario',
ADD COLUMN education_finished ENUM('Si', 'No') DEFAULT 'No',
ADD COLUMN degree_obtained VARCHAR(150) DEFAULT NULL,
ADD COLUMN institution VARCHAR(150) DEFAULT NULL,
ADD COLUMN book VARCHAR(50) DEFAULT NULL,
ADD COLUMN folio VARCHAR(50) DEFAULT NULL,
ADD COLUMN academic_cycle VARCHAR(50) DEFAULT NULL,
ADD COLUMN address_street VARCHAR(150) DEFAULT NULL,
ADD COLUMN address_number VARCHAR(20) DEFAULT NULL,
ADD COLUMN address_type ENUM('Casa', 'Departamento') DEFAULT 'Casa',
ADD COLUMN address_province VARCHAR(100) DEFAULT NULL,
ADD COLUMN address_locality VARCHAR(100) DEFAULT NULL,
ADD COLUMN address_zip_code VARCHAR(10) DEFAULT NULL,
ADD COLUMN phone_landline VARCHAR(50) DEFAULT NULL,
ADD COLUMN phone_mobile VARCHAR(50) DEFAULT NULL,
ADD COLUMN req_dni_photocopy BOOLEAN DEFAULT FALSE,
ADD COLUMN req_degree_photocopy BOOLEAN DEFAULT FALSE,
ADD COLUMN req_degree_photocopy_obs TEXT DEFAULT NULL,
ADD COLUMN req_two_photos BOOLEAN DEFAULT FALSE,
ADD COLUMN req_psychophysical BOOLEAN DEFAULT FALSE,
ADD COLUMN req_psychophysical_obs TEXT DEFAULT NULL,
ADD COLUMN req_vaccines BOOLEAN DEFAULT FALSE,
ADD COLUMN req_vaccines_obs TEXT DEFAULT NULL,
ADD COLUMN req_student_book BOOLEAN DEFAULT FALSE,
ADD COLUMN req_final_degree BOOLEAN DEFAULT FALSE,
ADD COLUMN req_final_degree_obs TEXT DEFAULT NULL,
ADD COLUMN found_institution JSON DEFAULT NULL,
ADD COLUMN notes TEXT DEFAULT NULL;
